---
apiVersion: v1
kind: Service
metadata:
  namespace: datadeck
  name: datadeck-svc
  labels:
    app.kubernetes.io/name: datadeck-svc
spec:
  selector:
    app: datadeck
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
      nodePort: 3000