---
apiVersion: v1
kind: Service
metadata:
  namespace: datadeck-dev
  name: datadeck-svc
spec:
  selector:
    app: datadeck
    env: dev
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
